# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install -e '.[tests]'
    - name: Lint with Ruff
      run: |
        ruff check .
    - name: Test with pytest
      run: |
        pytest
    - name: Test with snippets
      run: |
        cd snippets && AHEUI=../rpaheui.py ./test.sh --disable logo
    - name: Codecov
      run: bash <(curl -s https://codecov.io/bash)
  build-jit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
          submodules: true
      - name: Set up PyPy
        uses: actions/setup-python@v2
        with:
          python-version: pypy-2.7
      - uses: actions/checkout@master
        with:
          repository: pypy/pypy
          ref: release-pypy2.7-v7.3.15
          path: pypy
      - name: Build
        run: |
          export RPYTHON="pypy $GITHUB_WORKSPACE/pypy/rpython/bin/rpython"
          cd $GITHUB_WORKSPACE
          make
      - name: Test with snippets
        run: |
          cd "$GITHUB_WORKSPACE/snippets"
          AHEUI="$GITHUB_WORKSPACE/rpaheui-c" ./test.sh --disable logo integer
